Simple Perceptron Learning Algorithm

the perceptron algorithm is a simple and efficient linear classifier that is used to predict the output class of an input based on a linear combination of its features.
 It uses an activation function, to transform the weighted sum of the input features into an output that can be used for prediction.

initialized some instance variables including, weights, bias, learning rate, and epochs(iteration)

In [ ]:
import numpy as np

class Perceptron_My:

    def __init__(self, learning_rate=0.01, epochs=50):
        self.weights = None
        self.bias = None
        self.learning_rate = learning_rate
        self.epochs = epochs
    # heaviside activation function
    def activation(self, z):
      return np.heaviside(z, 0) # haviside(z) heaviside -> activation
    def fit(self, X, y):
        n_features = X.shape[1]

        # Initializing weights and bias
        self.weights = np.zeros((n_features))
        self.bias = 0

        # Iterating until the number of epochs
        for epoch in range(self.epochs):

            # Traversing through the entire training set
            for i in range(len(X)):
                z = np.dot(X, self.weights) + self.bias # Finding the dot product and adding the bias
                y_pred = self.activation(z) # Passing through an activation function

                #Updating weights and bias
                self.weights = self.weights + self.learning_rate * (y[i] - y_pred[i]) * X[i]
                self.bias = self.bias + self.learning_rate * (y[i] - y_pred[i])

        return self.weights, self.bias
    def predict(self, X):
        z = np.dot(X, self.weights) + self.bias
        return self.activation(z)

define the activation function method. The Heaviside activation method only takes one parameter, which is the weighted sum of inputs z, and returns the corresponding output.

training Perceptron,

Prediction method

Classifying Iris dataset using Perceptron

Loading the dataset

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()

Splitting the dataset

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split


# X = pd.DataFrame(iris.data, columns=iris.feature_names)
# y = pd.Series(iris.target, name='target')


X = iris.data # petal length, petal width
print(X)
y = iris.target
#y=iris.data[0,1,2].astype(np.int64)
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [ ]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 150 entries, 0 to 149
Series name: target
Non-Null Count  Dtype
--------------  -----
150 non-null    int64
dtypes: int64(1)
memory usage: 1.3 KB


Training and making predictions

In [ ]:
perceptron = Perceptron_My()
perceptron.fit(X_train, y_train)
pred = perceptron.predict(X_test)

how much accuracy we have got,

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(pred, y_test)



0.3

That's great we got an accuracy of 30%, changing the learning rate or the number of epochs will result in more accurate results.

> Indented block



Classification report

In [ ]:
from sklearn.metrics import classification_report

report = classification_report(pred, y_test, digits=2)
print(report)

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       1.00      0.30      0.46        30
         2.0       0.00      0.00      0.00         0

    accuracy                           0.30        30
   macro avg       0.33      0.10      0.15        30
weighted avg       1.00      0.30      0.46        30



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classifying Iris dataset using Scikit-learn Perceptron class

In [ ]:
from sklearn.linear_model import Perceptron


sk_perceptron = Perceptron()
sk_perceptron.fit(X_train, y_train)
sk_perceptron_pred = sk_perceptron.predict(X_test)

# Accuracy

accuracy_score(sk_perceptron_pred, y_test)

0.8

Limitations
Even though Perceptrons are considered great by researchers, they also find some limitations, First of all, it is a binary classifier, so they cannot be used for learning really complex data like natural language processing, speech recognition, etc. Moreover, most of the Linear models cannot solve the XOR problem and Perceptrons are also one of them.
But lately, after doing more research, scientists found that stacking multiple Perceptrons can solve most of the complex problems and the XOR problem as well. This results in an Artificial Neural Network known as Multilayer Perceptrons(MLP). MLP shows great success in solving more complex problems and learning really complex patterns in the training data.